######################################################################
# Automatically generated by qmake (2.01a) Mon May 6 00:01:56 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qt4display.h
SOURCES += filterQt4.cc qt4display.cc

mac {
  CONFIG -= app_bundle
}